project:
  type: book
  output-dir: docs

book:
  title: "GEOG370"
  author: "Julia Cardwell"
  date: "8/11/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - core.qmd
    - data.qmd
    - models.qmd
    - attributes.qmd
    - resolution.qmd
    - coordinate_systems.qmd
    - error.qmd
    - files.qmd
    - qgis.qmd
    - learning_qgis.qmd
    - doing_spatial_analysis.qmd
    - labs.qmd


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

