# QGIS Basics

Before any sort of analysis and visualization can take place, you must be extremely comfortable with creating projects, opening files, working with attributes, loading basemaps, and basic symbolization. Think of this chapter as your hands-on introduction to the essential building blocks of working with spatial data in QGIS. The sample data used in this chapter can be found [here](https://drive.google.com/drive/folders/16dvmblS9W8Hi0iaui6jw1vr5OGcWNUiR?usp=sharing). Download the folder, unzip it, and add the contents to your GEOG370/lab/lab_1/raw_data folder.

## [Starting a Project](https://drive.google.com/file/d/1HNCQfpApcvT_bYCXq5HrpwuO0BR8_seL/view?usp=sharing)

Every time you begin a new lab or analysis, you’ll create a new QGIS project file. This .qgz file stores the structure of your work: which layers you loaded, how you symbolized them, and what your map looked like when you last saved it. It’s like a snapshot of your workspace.QGIS projects do not store the data itself—they store file paths. If you move, rename, or delete your data after you’ve added it to a project, QGIS won’t be able to find it anymore. Always keep your data organized in a consistent folder structure (introduced in Chapter 8).

## [Adding a Basemap](https://drive.google.com/file/d/1anULPv8C_2ShLyzhYE6sbzLzj4AR6SpP/view?usp=sharing)

Once you’ve created a project, you typically want to add a basemap. **A basemap is a foundational map that provides geographic context for other data**. It is often a satellite image, topographic map, or streetmap. QGIS comes built in with two basemaps, which can be accessed in the XYZ Tiles in your Browser window. You can also add additional basemaps using the QMS plug-in (plug-ins add additional functionality to QGIS)

## [Adding Raster or Vector Data](https://drive.google.com/file/d/1t1D3TCC4VfkbhJ_UFFwH17vSut04w30A/view?usp=sharing)

Now that you have your project set up, you are ready to add some vector and raster data. You will add two datasets: a raster representing elevation in Orange County, and a vector representing census block groups across North Carolina. There are multiple ways to add data, but the simplest way is to use the Browser panel. [If you are missing your panels, watch this video.](https://drive.google.com/file/d/10be1iGWf4RApnKoFf3pflPVn_L_7NDBR/view?usp=sharing) 

Note on coordinate systems: In the “Adding Data” video, you may have noticed a pop-up asking you to “Select Transformation.” This happens when the Coordinate Reference System (CRS) of the map canvas is different from the CRS of the data you’re adding. For example, in the video, the bottom right corner shows that the map canvas is using EPSG:3857 (your project might use a different one). This is because the basemap I added at the start of the project is in EPSG:3857. This is NOT reprojecting the data and it is NOT changing the CRS of the base data. We will cover that later on. In general, I just select the first transformation option. 

## Working with Attributes 

When you read in vector data (census block groups), one of the first things that you should do is [explore the properties of the data, including looking at the data type of each of the fields and exploring the attribute table (including looking at selected features).](https://drive.google.com/file/d/1TnRS1U5XKcbFMu33MfqS4w6S_n5rUqSL/view?usp=sharing) One of the most powerful parts of GIS is connecting spatial features to tabular data. In vector files, each feature (a polygon, for example) is linked to a row in an attribute table that provides additional (non-spatial) information about the geographical feature.

You can add additional attributes in QGIS using the field calculator. For this lab, you should [to add a field](https://drive.google.com/file/d/14I1QCvfXSisWaGZC5hojAQJao837aeAV/view?usp=sharing) representing the population (in thousands) using the field calculator (note that you must always save edits and toggle editing off when done).

With raster data (elevation data), there is typically no separate attribute table. [To explore values, you will typically use symbology or the information tab](https://drive.google.com/file/d/19wNUsrbDnoJ5O4KnC5nmhVldOcXdkyaI/view?usp=sharing) (note that the layer must be selected in the browser for the information tab to select the correct feature).

## Basic Symbolization

Chances are, the symbolization that is automatically applied when you add your data into QGIS is not going to be sufficient. Symbology choices are some of the most important choices that you will make when creating maps. There are many symbology choices available in QGIS. You should symbolize your elevation and census data. Here are the basics of [changing vector](https://drive.google.com/file/d/1peIgBviXjJ_uX7EArwakNs4wJZrEXhRN/view?usp=sharing) and [raster symbology](https://drive.google.com/file/d/12GRmKnz2n01E2t6M9sDUNxyhAazprJfG/view?usp=sharing)

Explore these resources for more information:

-   [Lesson: Changing Raster Symbology](https://docs.qgis.org/3.40/en/docs/training_manual/rasters/changing_symbology.html)

-   [Lesson: Symbology](https://docs.qgis.org/3.40/en/docs/training_manual/basic_map/symbology.html)

## Adding Tabular Data and Executing Table Joins

As discussed in Chapter 6, sometimes geospatial data comes in a tabular format. [You can easily add tabular data that has a lat, lon fields by using the Data Source Manager.](https://drive.google.com/file/d/1FC5gqPed8LDbQr8q8MlVn1SwMJ-fsXhX/view?usp=sharing) For this project, you will add in tabular data representing the maximum temperature at North Carolina ASOS stations (weather stations) during a June 2024 heatwave.

Finally, [table joins](https://drive.google.com/file/d/1FC5gqPed8LDbQr8q8MlVn1SwMJ-fsXhX/view?usp=sharing) are an absolutely essential pre-processing step for many spatial analyses. A table join involves joining tabular data and spatial data based on a matching key. For instance, you might have data about geographical locations (for instance, census block groups) but the data doesn't actually have the geometry information. In this case, you could match census data to the census block group boundary file using a shared key (GEOID). For this to work in QGIS, it is required that the matching keys are exactly the same (which is often a problem) and are set as the same data type in QGIS. For this project, you will add census block group data that represents median income and join this to your census block group boundary file.
