# Working with Geographic Data in QGIS

QGIS is a GIS software that is free and open-source. It is true that Esri products are often considered the industry standard. I’ve heard concerns from students who worry that they won’t be prepared for a GIS career if they’ve only learned in QGIS. To this, I respond that understanding GIS conceptually– being able to form spatial questions, understanding the limits of data, selecting appropriate analytical tools– is far more important than expertise in a particular software. In reality, although they can look quite different, the most commonly used GIS softwares are extremely similar. Although the initial learning curve is steep, switching from one software to another is easy. Because practicing open science is important to me, I teach in QGIS. However, anything we do in QGIS could be easily translated to ArcGIS Pro. If you want help learning how to do so, I am always available.

We will be using the current Long Term Release version of QGIS (3.44.11 'Solothurn'), which can be downloaded [here](https://qgis.org/download/).

# QGIS 101

This class focuses on developing fluency with a relatively small set of common GIS tasks. The videos below demonstrate the complete set of GIS skills you will use throughout the course. In later chapters, you'll find additional videos that apply these same tasks to specific scenarios for practice, but the videos here serve as your primary reference.

## Preparing Data

### [Table Join (Vector)](https://drive.google.com/file/d/1wDdrr8x0KED4cMuUlS1HXK2ricg2grHX/view?usp=drive_link)

A table join adds attributes from a non-spatial file to a spatial file based on a common key field between the two datasets.

### [Reproject (Vector/Raster)](https://drive.google.com/file/d/1E9rchAaKoqPhxPoT71oSawh2NzbH2czy/view?usp=drive_link)

Converts the CRS of a dataset to another CRS

### [Spatialize Data (Vector)](https://drive.google.com/file/d/1rRcAUQ6_pno0pf447JsAOuLJzIHkRaLp/view?usp=drive_link)

Turns a non-spatial file into a spatial format using latitude/longitude fields in the data

### [Create New Field (Vector)](https://drive.google.com/file/d/1Ur1GgWSs_KeocuxDAmQ15DMcedjSGy3R/view?usp=drive_link)

Calculates a new field in an existing dataset using the Field Calculator

### Clip ([Vector](https://drive.google.com/file/d/1dJbfsOMks50s3yf7v3tm5obJSv6T3PPk/view?usp=drive_link)/[Raster](https://drive.google.com/file/d/1rZbCcp_qSrwVeZVwT8FhMIa_KJyFlG1S/view?usp=drive_link))

Cuts out an input layer based on a defined boundary (either another layer or an extent)

### [Aggregate (Vector)](https://drive.google.com/file/d/1j-pD3ELZr9cIvvXI5IVT6EArnV3kRPiH/view?usp=drive_link)

Aggregates features based on an attribute value (can summarize other attributes).

## Querying

### [Select by Attribute (Vector)](https://drive.google.com/file/d/1tsLAsSVz-X7-s3lqBQN-f7nBrV7ptraj/view?usp=drive_link)

Selects features based on a query of a field or multiple fields

### [Select by Location (Vector)](https://drive.google.com/file/d/15PDXrg1jQJ5lr2LRaneXBHhR2dKyztru/view?usp=drive_link)

Selects features based on a spatial query of another layer

## Spatial Analysis

### [Buffer (Vector)](https://drive.google.com/file/d/13vrxIFaSRnah1MiBULhefU9jkRItu-IT/view?usp=drive_link)

Adds a polygon zone at a specified distance around points, lines, or polygons

### [Intersect (Vector)](https://drive.google.com/file/d/1IVsHq5mzMyi8nok4KI8IXX7KHevbDzrt/view?usp=drive_link)

Calculates the overlap between two or more layers

### [Spatial Join (Vector)](https://drive.google.com/file/d/1-JXo6Dq89jd9YHcDLljvYsXNOWKDzm6e/view?usp=drive_link)

Combines attributes of two spatial layers based on their location

### [Reclassify Raster (Raster)](https://drive.google.com/file/d/1I-_ueoNOlFVVbMp5Djrjr-lNSPG4AUqA/view?usp=drive_link)

Changes raster values to new values based on set rules

### [Raster Math (Raster)](https://drive.google.com/file/d/1GYpL4OP2HsYWTwLyYMcKs_MGJbW66xzR/view?usp=drive_link)

Performs mathematical operations on two or more raster layers

### [Zonal Statistics (Raster)](https://drive.google.com/file/d/1JOZagkkmZNkDn3F-80RPjY941kLa3AkQ/view?usp=drive_link)

Calculate summary statistics for raster dataset cells that fall within specific vector zones
