theme: jekyll-theme-primer
exclude:
  - .DS_Store
  - images/attributes.png
  - images/autocorr.png
  - images/hosp.png
  - images/raster_multiple_resolutions.png
  - images/tobler.jpg
  - images/zone.png
  - site_libs/Leaflet*
  - site_libs/Proj4Leaflet-*
  - site_libs/htmltools-fill-*
  - site_libs/htmlwidgets-*
  - site_libs/jquery-*
  - site_libs/leaflet-*
  - site_libs/leaflet-binding-*
  - site_libs/leaflet-providers-*
  - site_libs/leaflet-providers-plugin-*
  - site_libs/leafletfix-*
  - site_libs/proj4-*
  - site_libs/rstudio_leaflet-*
