<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Thinking Spatially – GEOG370</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./core.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Thinking Spatially</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">GEOG370</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./core.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Thinking Spatially</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is Geographic Data?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial Data Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./attributes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Understanding Attributes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Resolution in Geographic Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coordinate_systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Coordinate Systems and Projections</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Accuracy, Error, and Precision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Managing Files</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qgis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Working with Geographic Data in QGIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./learning_qgis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">QGIS Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./doing_spatial_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Doing Spatial Analysis in QGIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Labs</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-is-a-geographic-information-system" id="toc-what-is-a-geographic-information-system" class="nav-link active" data-scroll-target="#what-is-a-geographic-information-system"><span class="header-section-number">2.1</span> What is a Geographic Information System</a>
  <ul class="collapse">
  <li><a href="#the-layer-model" id="toc-the-layer-model" class="nav-link" data-scroll-target="#the-layer-model"><span class="header-section-number">2.1.1</span> The Layer Model</a></li>
  </ul></li>
  <li><a href="#core-spatial-concepts" id="toc-core-spatial-concepts" class="nav-link" data-scroll-target="#core-spatial-concepts"><span class="header-section-number">2.2</span> Core Spatial Concepts</a>
  <ul class="collapse">
  <li><a href="#location" id="toc-location" class="nav-link" data-scroll-target="#location"><span class="header-section-number">2.2.1</span> Location</a></li>
  <li><a href="#distance" id="toc-distance" class="nav-link" data-scroll-target="#distance"><span class="header-section-number">2.2.2</span> Distance</a></li>
  <li><a href="#distribution" id="toc-distribution" class="nav-link" data-scroll-target="#distribution"><span class="header-section-number">2.2.3</span> Distribution</a></li>
  <li><a href="#spatial-relationships" id="toc-spatial-relationships" class="nav-link" data-scroll-target="#spatial-relationships"><span class="header-section-number">2.2.4</span> Spatial Relationships</a></li>
  <li><a href="#spatial-processes" id="toc-spatial-processes" class="nav-link" data-scroll-target="#spatial-processes"><span class="header-section-number">2.2.5</span> Spatial Processes</a></li>
  </ul></li>
  <li><a href="#spatial-is-special" id="toc-spatial-is-special" class="nav-link" data-scroll-target="#spatial-is-special"><span class="header-section-number">2.3</span> Spatial Is Special</a>
  <ul class="collapse">
  <li><a href="#spatial-dependence" id="toc-spatial-dependence" class="nav-link" data-scroll-target="#spatial-dependence"><span class="header-section-number">2.3.1</span> Spatial Dependence</a></li>
  <li><a href="#spatial-non-stationarity" id="toc-spatial-non-stationarity" class="nav-link" data-scroll-target="#spatial-non-stationarity"><span class="header-section-number">2.3.2</span> Spatial Non-Stationarity</a></li>
  <li><a href="#scale-effects" id="toc-scale-effects" class="nav-link" data-scroll-target="#scale-effects"><span class="header-section-number">2.3.3</span> Scale Effects</a></li>
  <li><a href="#modifiable-areal-unit-problem" id="toc-modifiable-areal-unit-problem" class="nav-link" data-scroll-target="#modifiable-areal-unit-problem"><span class="header-section-number">2.3.4</span> Modifiable Areal Unit Problem</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Thinking Spatially</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Many disciplines study people, places, and environments. Therefore, it is not the subject matter that differentiates geography from a field like Environmental Science or Sociology, but rather, the guiding framework. Geography is distinctive because it focuses on how relationships in space influence how the world works.</p>
<p>Geography begins with the fact that where something occurs often matters. The location of a hospital influences who can access healthcare. The location of a factory influences exposure to pollution. The location of a business influences its customers. The location of a wetland influences patterns of flooding and biodiversity.</p>
<p>A geographer looking at housing prices, disease outbreaks, wildfires, or demographic change in a city asks a set of surprisingly similar questions:</p>
<ul>
<li>Where is it located?</li>
<li>What pattern does it form?</li>
<li>Why does that pattern exist?</li>
<li>What are the consequences of that pattern?</li>
</ul>
<p>The goal of Geographic Information Science is to develop methods for answering these questions using spatial data.</p>
<section id="what-is-a-geographic-information-system" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="what-is-a-geographic-information-system"><span class="header-section-number">2.1</span> What is a Geographic Information System</h2>
<p>One common method for exploring spatial questions (using geographic data) is a Geographic Information System (GIS). A GIS is an integrated framework for exploring spatial questions. It is built around combining hardware, software, data, people, and methodologies to analyze space. In this course, we’ll use GIS as a tool to help us examine geographic data, but the focus is not on learning GIS software in depth. Rather, we’ll use it to support broader learning about geographic information and spatial thinking.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Component</td>
<td>Description</td>
</tr>
<tr class="even">
<td>Hardware</td>
<td>Physical infrastructure used for GIS. This includes local computers, servers, data collection devices, etc.</td>
</tr>
<tr class="odd">
<td>Software</td>
<td>Applications and platforms used to analyze, visualize, and manage geographic data.&nbsp;</td>
</tr>
<tr class="even">
<td>Data</td>
<td>Data suitable for analysis in a GIS requires a locational component</td>
</tr>
<tr class="odd">
<td>People</td>
<td>Users, developers, analysts, and decision-makers who interact with GIS.</td>
</tr>
<tr class="even">
<td>Methodologies</td>
<td>Techniques that are implemented inside a GIS to process data and answer spatial questions.&nbsp;</td>
</tr>
</tbody>
</table>
<section id="the-layer-model" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="the-layer-model"><span class="header-section-number">2.1.1</span> The Layer Model</h3>
<p>The most basic unit of geographic information is a feature. A feature is any object, event, or phenomenon that has a location. Features can represent a wide variety of things. A building, road, tree, river, census tract, wildfire, or weather station can all be represented as features in a GIS.</p>
<p>Features are then typically organized into layers. A layer is a collection of similar features representing a particular type of geographic phenomenon. For example, a city GIS database might contain separate layers for roads, parcels, streams, schools, and parks. Layers allow us to organize geographic information and examine relationships between different aspects of the landscape.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/layer_model.jpg" class="img-fluid figure-img" width="396"></p>
<figcaption>The Layer Model (from Essentials of Geographic Information Fig 1.8, CC BY-NC-SA 3.0)</figcaption>
</figure>
</div>
</section>
</section>
<section id="core-spatial-concepts" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="core-spatial-concepts"><span class="header-section-number">2.2</span> Core Spatial Concepts</h2>
<section id="location" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="location"><span class="header-section-number">2.2.1</span> Location</h3>
<p>Location describes where something is. Location can be described in <strong>absolute</strong> terms (e.g.&nbsp;latitude and longitude coordinates), or in <strong>relative</strong> terms (e.g.&nbsp;next to campus). GIS is fundamentally built around location. Every feature in a GIS dataset has a location that allows it to be mapped, analyzed, and related to other features.</p>
</section>
<section id="distance" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="distance"><span class="header-section-number">2.2.2</span> Distance</h3>
<p>Distance describes how far apart features are. Distance influences movement, interaction, accessibility, and many other geographic processes. Because distance shapes how locations influence one another, it is one of the most important concepts in geography.</p>
<p>Geographer Waldo Tobler summarized this idea in what became known as the First Law of Geography: “Everything is related to everything else, but near things are more related than distant things.” This principle suggests that nearby locations often exert stronger influence on one another than distant locations. Consider the spread of influenza through a city. Neighborhoods near an outbreak are generally more likely to experience infections than neighborhoods located farther away because people interact most frequently with those who are nearby.</p>
<p>This tendency for interaction to decrease with increasing distance is known as distance decay. Distance decay occurs because distance introduces costs. Traveling farther generally requires more time, money, effort, or energy. As these costs increase, interactions often become less frequent. For example, most people regularly visit nearby grocery stores because they are easier to reach.</p>
</section>
<section id="distribution" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="distribution"><span class="header-section-number">2.2.3</span> Distribution</h3>
<p>Distribution refers to the arrangement of features across space. Features may be clustered, dispersed, or randomly distributed. Recognizing spatial patterns is one of the central goals of spatial analysis. For example:</p>
<ul>
<li>Retail stores often cluster near major roads</li>
<li>Trees in an orchard are intentionally dispersed at regular intervals</li>
<li>The dispersal of seeds from a single plant is often random</li>
</ul>
</section>
<section id="spatial-relationships" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="spatial-relationships"><span class="header-section-number">2.2.4</span> Spatial Relationships</h3>
<p>Things do not exist in isolation across space. Instead, features are connected through spatial relationships. Important spatial relationships include:</p>
<ul>
<li>Proximity (near/far)</li>
<li>Adjacency (sharing a boundary)</li>
<li>Containment (inside/outside)</li>
<li>Overlap</li>
<li>Connectivity</li>
</ul>
<p>These relationships allow GIS to answer questions like:</p>
<ul>
<li>Which neighborhoods are within a mile of a park?</li>
<li>What buildings fall inside a floodplain?</li>
<li>Which roads connect to a highway?</li>
</ul>
</section>
<section id="spatial-processes" class="level3" data-number="2.2.5">
<h3 data-number="2.2.5" class="anchored" data-anchor-id="spatial-processes"><span class="header-section-number">2.2.5</span> Spatial Processes</h3>
<p>Spatial processes are the mechanisms that create spatial patterns. Spatial patterns emerge because location, distance, proximity, or connectivity influence how a process operates.</p>
<p>Consider home values within a city. Housing prices are rarely distributed randomly across space. Instead, they are influenced by a variety of factors that operate geographically, such as accessibility to employment centers, proximity to parks and schools, neighborhood change, and local zoning regulations. Together, these processes create the spatial patterns we observe.</p>
<p>One common spatial process is <strong>diffusion</strong>, where something spreads from one location to nearby locations. Diseases often spread through contact between nearby individuals. New housing developments frequently stimulate additional development in surrounding areas. Because nearby locations often influence one another, diffusion commonly produces clustered spatial patterns.</p>
<p>Spatial patterns can also emerge from <strong>environmental constraints</strong>. Physical characteristics of the environment influence where activities can occur and how landscapes develop. Steep slopes may limit development, climate influences vegetation patterns, and water availability affects agricultural production. In these cases, the physical environment shapes the distribution of both human and natural phenomena.</p>
<p>Many spatial patterns are also produced by <strong>social and economic processes</strong>. People tend to live near employment opportunities, transportation infrastructure, family networks, and communities with similar social or cultural characteristics. Businesses often locate near customers, suppliers, and major transportation routes. These decisions create concentrations of population, economic activity, wealth, and land uses across space.</p>
<p>Finally, spatial patterns are frequently shaped by i<strong>nstitutions and systems of governance</strong>. Zoning regulations, school attendance boundaries, taxation districts, transportation investments, and protected areas all influence how people and resources are distributed. These policies create spatial differences that can persist for decades and significantly shape the landscapes we observe today.</p>
</section>
</section>
<section id="spatial-is-special" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="spatial-is-special"><span class="header-section-number">2.3</span> Spatial Is Special</h2>
<section id="spatial-dependence" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="spatial-dependence"><span class="header-section-number">2.3.1</span> Spatial Dependence</h3>
<p>Tobler’s First Law of Geography states that “everything is related to everything else, but near things are more related than distant things”. Spatial dependence arises because the value of a variable at one location is often influenced by nearby locations. Spatial dependence emerges as a result of spatial processes. Spatial dependence can be strongly positive (which results in a clustered pattern), weak (which results in a random spatial pattern), or strongly negative (which results in a dispersed pattern).</p>
<p>The map below shows median home value by census tract in the Triangle region of North Carolina. This is an example of areal spatial data. Looking at this map, we can determine that there are clear clusters of positive and negative values (i.e.&nbsp;median home value is more similar in nearer locations).</p>
<p><img src="images/clipboard-528162725.png" class="img-fluid" width="576"></p>
<p>In contrast, many species distributions, especially of territorial species, result in a dispersed spatial pattern. Individuals or groups maintain a certain distance from one another to reduce competition for resources such as food, nesting sites, or mating opportunities. Examples include wolves, foxes, and certain bird species, where each territory is spaced to minimize overlap with neighbors.</p>
<p>If spatial autocorrelation is weak, it means that nearby locations are not consistently similar or dissimilar. This can happen when the underlying process is essentially random, when the factors influencing it are not spatially structured, or when multiple processes with opposing effects cancel each other out. Measurement or scale issues can also weaken apparent spatial dependence; for example, aggregating data over large regions can mask local patterns, making the distribution appear random.</p>
</section>
<section id="spatial-non-stationarity" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="spatial-non-stationarity"><span class="header-section-number">2.3.2</span> Spatial Non-Stationarity</h3>
<p>Spatial patterns are caused by a combination of non-spatial and spatial processes. A spatial process is a mechanism, or set of mechanisms, that operates through space. This means that the location, proximity, or connectivity of features matters for how the process operates (i.e.&nbsp;the process itself depends on spatial relationships). This differs fundamentally from a non-spatial process, in which the outcome is independent of location or spatial arrangement.</p>
<p>Taking our example of median home value, we could consider several potential spatial processes that contribute to the clustered spatial pattern, including proximity effects (the value of a home is influenced by nearby properties) and accessibility (homes closer to transit, downtown areas, or commercial hubs are often more valuable). However, the observed pattern is also influenced by non-spatial processes, such as home size, home age, construction quality, and the number of bedrooms.</p>
<p>An important characteristic of spatial processes is that they are often <strong>non-stationary</strong>. This means that the way a process operates can change across space, so the relationships, mechanisms, or effects observed in one location may not be the same in another. For example, home values in one part of a city may be influenced primarily by access to employment and public transit, whereas in another part they may be driven more by school quality or proximity to parks and other natural amenities. More generally, non-stationarity can mean that the same process has different effects in different places, or that entirely different processes are operating across the study area. Recognizing non-stationarity is crucial for spatial analysis because models that assume a single, uniform process operating everywhere (global models) may fail to accurately capture these spatially varying relationships.</p>
</section>
<section id="scale-effects" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="scale-effects"><span class="header-section-number">2.3.3</span> Scale Effects</h3>
<p>Spatial processes also differ across scales. For instance, we can consider that there are spatial processes at the local, city, or state level that might influence home value. At the local level, processes such as neighborhood clustering of high-amenity areas, street connectivity, or proximity to parks can influence home values. At the city level, processes like zoning, transit accessibility, or distribution of commercial centers shape housing prices across neighborhoods. At the state or regional level, spatial processes include the distribution of economic hubs, in-migration, and regional commuting flow. Because spatial processes differ across scales, analysis must account for scale to accurately capture the mechanisms influencing space.</p>
</section>
<section id="modifiable-areal-unit-problem" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="modifiable-areal-unit-problem"><span class="header-section-number">2.3.4</span> Modifiable Areal Unit Problem</h3>
<p>Individual (or point-level) spatial data is often aggregated to areal units. This happens for several reasons:</p>
<ul>
<li>Privacy
<ul>
<li>Aggregating data protects sensitive information about individuals by reporting only summary values for larger areas</li>
</ul></li>
<li>Data availability
<ul>
<li>Some data are only measured or published at aggregated levels</li>
</ul></li>
<li>Analytical convenience
<ul>
<li>Aggregating data reduces complexity and makes spatial analysis more computationally manageable</li>
</ul></li>
<li>Alignment with policy or planning units
<ul>
<li>Many decisions (for instance, in urban planning, public health, or transportation) are made at administrative or political boundaries</li>
</ul></li>
</ul>
<p>While aggregating data is often necessary or useful, it introduces the Modifiable Areal Unit Problem (MAUP), where the choice of spatial units (size or boundaries) can influence statistical results and spatial patterns. These results can change significantly depending on how the boundaries are drawn (zone effect) and how large or small the units are (scale effect).</p>
<p>Consider the summary statistics for percent poverty across North Carolina zip codes vs.&nbsp;counties to see the impact of the scale effect:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Aggregation Unit</th>
<th>Mean</th>
<th>Median</th>
<th>Min</th>
<th>Max</th>
<th>St.&nbsp;Dev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zip Code</td>
<td>25.33</td>
<td>23.76</td>
<td>0</td>
<td>100</td>
<td>13.82</td>
</tr>
<tr class="even">
<td>County</td>
<td>26.46</td>
<td>25.48</td>
<td>12.34</td>
<td>40.83</td>
<td>6.58</td>
</tr>
</tbody>
</table>
<p>Aggregating data into larger units can smooth out local variation and reduce variability. For example, comparing the standard deviation at the zip code (13.82) to the county (6.58) shows that smaller units capture more heterogeneity.</p>
<p>Because of the MAUP, we need to be careful when interpreting aggregated data, given that patterns observed at one scale or within a particular zoning scheme may not hold at another. Since spatial patterns are often scale-dependent, one way to mitigate the effects of the MAUP is to align the selection of areal units with the hypothesized scale of the underlying process</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data.html" class="pagination-link" aria-label="What is Geographic Data?">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is Geographic Data?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>